In [18]:
#A1. OPERATIONS: append, extend, insert, remove, pop, clear, index, count, sort, and reverse


l1=[1,2,3,4,5]
l2=[6]
print(f"List1={l1} and List2={l2}")
l1.append(l2)
print(f"Appending 2 lists :{l1}")
l1.extend(l2)
print(f"Extend :{l1}")
l1.insert(2,10)
print(f"Inserting :{l1}")
l1.remove(1)
print(f"Remove :{l1}")
l1.pop()
l1.pop()
print(f"pop :After popping,list is :{l1}")
print(f"Index :{l1.index(10)}")
print(f"Count :{l1.count(2)}")
l1.sort()
print(f"Sort:{l1}")
l1.reverse()
print(f"Reverse :{l1}")
l1.clear()
print(f"Clear:{l1}")


List1=[1, 2, 3, 4, 5] and List2=[6]
Appending 2 lists :[1, 2, 3, 4, 5, [6]]
Extend :[1, 2, 3, 4, 5, [6], 6]
Inserting :[1, 2, 10, 3, 4, 5, [6], 6]
Remove :[2, 10, 3, 4, 5, [6], 6]
pop :After popping,list is :[2, 10, 3, 4, 5]
Index :1
Count :1
Sort:[2, 3, 4, 5, 10]
Reverse :[10, 5, 4, 3, 2]
Clear:[]


In [ ]:
#A2. Changes in a TUPLE


t=("rabbit","peacock","lion")
t[1]="dog"

In [ ]:
#A3. Duplicates in SET

s={1,2,3,3,4,4,5}
print(s)

In [2]:
# A4. Changes in DICTIONARY
d={"name":"Bunny",
   "age":20,
   "city":"banglore"}
d["age"]=22
d["email"]="abc@gmail.com"
print(d)

{'name': 'Bunny', 'age': 22, 'city': 'banglore', 'email': 'abc@gmail.com'}


In [3]:
#A5. ELIGIBLE to vote

age=int(input())
if age>=18:
    print("Eligible")
else:
    print("Not Eligible")

 16


Not Eligible


In [4]:
#A6. GRADES

marks=int(input())
if marks>=90:
    print("Grade-A")
elif marks>=75 and marks<=89:
    print("Grade-B")
elif marks>=50 and marks<=74:
    print("Grade-C")    
else:
    print("Fail")


 70


Grade-C


In [5]:
#A7. Number is +ve/-ve ,even/odd, or 0

n=int(input())
if(n>0 and n%2==0):
    print(f"{n} is positive and even")
elif(n>0 and n%2!=0):
    print(f"{n} is positive and odd")
elif(n<0 and n%2==0):
    print(f"{n} is negative and even")
elif(n<0 and n%2!=0):
    print(f"{n} is negative and odd")
else:
    print(f"entered number is 0")

 5


5 is positive and odd


In [6]:
#B8. NUMPY

import numpy as np
a=np.array(5)
print(f"Scalar :{a}")
a=[1,2,3,4,5]
print(f"Array :{a}")
b=np.arange(10,61,10).reshape(2,3)
print(f"2x3 matrix with step 10 from 10 to 60 :{b}")

Scalar :5
Array :[1, 2, 3, 4, 5]
2x3 matrix with step 10 from 10 to 60 :[[10 20 30]
 [40 50 60]]


In [7]:
#B9. A 4x4 matrix of RANDOM

import numpy as np
import random
a=np.random.randint(1,100,size=(4,4))
print(a)

[[52 13 81 15]
 [98  1 68 14]
 [95 16 47 75]
 [95 57 54 93]]


In [8]:
#B10. Create PANDAS DATAFRAME

import pandas as pd
import numpy as np

arr=np.arange(1,10).reshape(3,3)
df=pd.DataFrame(arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [24]:
#C11. Exploring Pandas

import pandas as pd
df=pd.DataFrame([["A",20,"bgl",20000],
                 ["B",21,"bgl",30000],
                 ["C",22,"HYD",25000],
                 ["D",23,"chn",40000],
                 ["E",20,"pune"],
                 ["F",21,"hyd",50000],
                 ["C",22,"HYD",25000],
                 ["H",23,"pune",40000],
                 ["I",18,"chn"],
                 ["J",20,"hyd",45000]],
                 columns=["Name","Age","City","Salary"])
print("DATA:",df)

print("INFO:",df.info())
print("DESCRIBE:",df.describe())

a=pd.DataFrame(df,columns=["Name","City"])
#print(df[["Name","City"]])

print("SELECTED COLUMNS:",a)
df.drop("City",axis=1,inplace=True)
print(df)
df.fillna(df["Salary"].mean(),inplace=True)
print(df)

DATA:   Name  Age  City   Salary
0    A   20   bgl  20000.0
1    B   21   bgl  30000.0
2    C   22   HYD  25000.0
3    D   23   chn  40000.0
4    E   20  pune      NaN
5    F   21   hyd  50000.0
6    C   22   HYD  25000.0
7    H   23  pune  40000.0
8    I   18   chn      NaN
9    J   20   hyd  45000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
INFO: None
DESCRIBE:              Age        Salary
count  10.000000      8.000000
mean   21.000000  34375.000000
std     1.563472  10835.622469
min    18.000000  20000.000000
25%    20.000000  25000.000000
50%    21.000000  35000.000000
75%    22.000000  41250.000000
max    23.000000  50000.000000
SELECTE